Feat/snap types restructure
blockchain-lab-um/ssi-snap pull request #63
Opened 2022-12-01 13:03 UTC by tadejpodrekar

Moved reusable types from the connector and snap to the types package.
Corrected imports to use types from packages.

2022-12-01 15:00 UTC, andyv09 requested changes

2022-12-01 15:00 UTC, andyv09 commented on packages/types/methods.ts
> +}
Update these methods to match the ones from snap (use interfaces for params from ./params)

2022-12-01 15:00 UTC, andyv09 commented on packages/types/requests.ts
> +  | GetAvailableVCStores;
change with latest methods from snap

2022-12-01 15:00 UTC, andyv09 commented on packages/types/snapApi.ts
> +}
update this aswell

2022-12-02 08:12 UTC, andyv09 requested changes

2022-12-02 08:12 UTC, andyv09 commented on packages/types/methods.ts
> +export interface QuerryVCs {
Query*

2022-12-02 08:30 UTC, andyv09 approved these changes

2022-12-02 14:26 UTC, martines3000 commented on packages/types/constants.ts
> +// Source: https://github.com/multiformats/multicodec/blob/master/table.csv
We don't need to split this. You can leave it in snap.

2022-12-02 14:27 UTC, martines3000 commented on packages/types/params.ts
> +  options?: {
```ts
type DeleteVCOptions = {
    store?: AvailableVCStores | [AvailableVCStores];
}
```

2022-12-02 14:29 UTC, martines3000 commented on packages/types/params.ts
> +  proofOptions?: {
Maybe split to separate type `proofOptions`

2022-12-03 17:17 UTC, martines3000 commented on packages/types/constants.ts
> +// Source: https://github.com/multiformats/multicodec/blob/master/table.csv
fixed

2022-12-03 17:20 UTC, merged